{
 "title": "OPNsense Suricata",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "InfluxDB", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Suricata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Alert Category",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_category\")\n  |> map(fn: (r) => ({ r with _count: r[\"_value\"]}))\n  |> group(columns: [\"_value\"])\n  |> count(column: \"_count\")\n  |> group()\n  |> sort(desc:true, columns: [\"_count\"])\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Top Source IP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_category\")\n  |> map(fn: (r) => ({ r with _count: r[\"src_ip\"]}))\n  |> group(columns: [\"src_ip\"])\n  |> count(column: \"_count\")\n  |> group()\n  |> sort(desc:true, columns: [\"_count\"])\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Top 10 Destination Ports",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_category\")\n  |> map(fn: (r) => ({ r with _count: r[\"dest_port\"]}))\n  |> group(columns: [\"dest_port\"])\n  |> count(column: \"_count\")\n  |> group()\n  |> sort(desc:true, columns: [\"_count\"])\n  |> limit(n: 10)"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"proto\")\n  |> map(fn: (r) => ({ r with _count: r[\"_value\"]}))\n  |> group(columns: [\"_value\"])\n  |> count(column: \"_count\")\n  |> group()\n  |> sort(desc:true, columns: [\"_count\"])"
    }
   ]
  },
  {
   "title": "Top Alert Signature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_signature\")\n  |> map(fn: (r) => ({ r with _count: r[\"_value\"]}))\n  |> group(columns: [\"_value\"])\n  |> count(column: \"_count\")\n  |> group()\n  |> sort(desc:true, columns: [\"_count\"])\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Top Destination IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_category\")\n  |> map(fn: (r) => ({ r with _count: r[\"dest_ip\"]}))\n  |> group(columns: [\"dest_ip\"])\n  |> count(column: \"_count\")\n  |> group()\n  |> sort(desc:true, columns: [\"_count\"])\n  |> limit(n:1)"
    }
   ]
  },
  {
   "title": "Top 10 Alert Categories",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_category\")\n  |> map(fn: (r) => ({ r with _count: r[\"_value\"]}))\n  |> group(columns: [\"_value\"])\n  |> count(column: \"_count\")\n  |> group()\n  |> sort(desc:true, columns: [\"_count\"])\n  |> limit(n:10)"
    }
   ]
  },
  {
   "title": "Top 10 Alert Signatures",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"suricata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_signature\")\n  |> map(fn: (r) => ({ r with _count: r[\"_value\"]}))\n  |> group(columns: [\"_value\"])\n  |> count(column: \"_count\")\n  |> group()\n  |> sort(desc:true, columns: [\"_count\"])\n  |> limit(n:10)"
    }
   ]
  },
  {
   "title": "Alert Logs",
   "type": "table",
   "description": "Last 100 events, newest on top",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"suricata\")\n  |> filter(fn: (r) => r._field == \"alert_signature\" or r._field == \"alert_action\" or r._field == \"alert_signature_id\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 100)"
    }
   ]
  }
 ]
}